name = "chatapp"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
assets.directory = ".cloudflare/public"
assets.binding = "ASSETS"

[observability]
enabled = true
head_sampling_rate = 1
